In [1]:
!pip install numpy

In [2]:
import numpy as np
a= np.random.randint(100,500,(30,5))
avg_a = np.mean(a, axis = 0)
print(f'Average Stock prices: {avg_a}')


max_a = np.max(a)
row_index, col_index = np.where(a == max_a)
print(f'Highest price recorded : {max_a} at Day {row_index[0]+1}, company {col_index[0]+1}')

min_prices = np.min(a, axis=0)
max_prices = np.max(a, axis=0)
normalized_prices = (a - min_prices) / (max_prices - min_prices)
print(f'Normalised prices: {normalized_prices}')
risk = a[a<200]
for i in risk:
    r_index,c_index = np.where(a == i)
    print( f'Risky Investment on Day: {r_index[0]+1} of Investment: {i}, by company {c_index[0]+1}')


Average Stock prices: [269.76666667 283.9        305.23333333 352.23333333 295.3       ]
Highest price recorded : 498 at Day 2, company 2
Normalised prices: [[0.3133515  0.58701299 0.00288184 0.60422164 0.81117021]
 [0.82833787 1.         0.14121037 0.81794195 0.60904255]
 [0.65122616 0.71168831 0.3054755  0.80474934 0.6037234 ]
 [0.17711172 0.52727273 0.55907781 1.         0.        ]
 [0.         0.86493506 0.28242075 0.9525066  0.46542553]
 [0.73569482 0.12727273 0.36311239 0.55672823 0.83244681]
 [0.76294278 0.63116883 0.8962536  0.28759894 0.36702128]
 [0.75476839 0.83376623 0.83861671 0.5171504  0.08510638]
 [0.02179837 0.25974026 0.4610951  0.69129288 0.35638298]
 [0.42506812 0.04935065 0.71757925 0.55672823 0.10638298]
 [0.3760218  0.03376623 0.33429395 0.90501319 0.86968085]
 [0.54223433 0.12207792 0.11527378 0.88390501 0.73138298]
 [0.29155313 0.2        0.72910663 0.60422164 0.39361702]
 [0.29972752 0.43376623 0.09510086 0.72823219 0.39095745]
 [0.09536785 0.24415584 0.95677

In [101]:
import numpy as np
arr = np.random.randint( 0,50, (6,3))
total = np.sum(arr, axis = 0)
print(f'Total resources needed (tons): Oxygen: {total[0]}, Water: {total[1]}, Food: {total[2]}')
max_con = np.max(arr)
r_index,c_index = np.where(arr == max_con)

print(f'Highest consumption in a month: {c_index[0]} ({max_con} in the month {r_index[0]})')

Total resources needed (tons): Oxygen: 148, Water: 173, Food: 75
Highest consumption in a month: 1 (46 in the month 2)
